name: bloc_clean_architecture
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.6
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
